// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interface/facade/rpc/proto/leave.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApprovalTypes int32

const (
	ApprovalTypes_APPROVING ApprovalTypes = 0
	ApprovalTypes_APPROVED  ApprovalTypes = 1
	ApprovalTypes_REJECTED  ApprovalTypes = 2
)

var ApprovalTypes_name = map[int32]string{
	0: "APPROVING",
	1: "APPROVED",
	2: "REJECTED",
}

var ApprovalTypes_value = map[string]int32{
	"APPROVING": 0,
	"APPROVED":  1,
	"REJECTED":  2,
}

func (x ApprovalTypes) String() string {
	return proto.EnumName(ApprovalTypes_name, int32(x))
}

func (ApprovalTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fda2757050484027, []int{0}
}

type CreateLeaveRequest struct {
	ApplicantID          int32         `protobuf:"varint,1,opt,name=ApplicantID,proto3" json:"ApplicantID,omitempty"`
	ApproverID           int32         `protobuf:"varint,2,opt,name=ApproverID,proto3" json:"ApproverID,omitempty"`
	ApprovalType         ApprovalTypes `protobuf:"varint,3,opt,name=ApprovalType,proto3,enum=interface.dto.proto.ApprovalTypes" json:"ApprovalType,omitempty"`
	StartTime            string        `protobuf:"bytes,4,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              string        `protobuf:"bytes,5,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateLeaveRequest) Reset()         { *m = CreateLeaveRequest{} }
func (m *CreateLeaveRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLeaveRequest) ProtoMessage()    {}
func (*CreateLeaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fda2757050484027, []int{0}
}

func (m *CreateLeaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLeaveRequest.Unmarshal(m, b)
}
func (m *CreateLeaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLeaveRequest.Marshal(b, m, deterministic)
}
func (m *CreateLeaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLeaveRequest.Merge(m, src)
}
func (m *CreateLeaveRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLeaveRequest.Size(m)
}
func (m *CreateLeaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLeaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLeaveRequest proto.InternalMessageInfo

func (m *CreateLeaveRequest) GetApplicantID() int32 {
	if m != nil {
		return m.ApplicantID
	}
	return 0
}

func (m *CreateLeaveRequest) GetApproverID() int32 {
	if m != nil {
		return m.ApproverID
	}
	return 0
}

func (m *CreateLeaveRequest) GetApprovalType() ApprovalTypes {
	if m != nil {
		return m.ApprovalType
	}
	return ApprovalTypes_APPROVING
}

func (m *CreateLeaveRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *CreateLeaveRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type CreateLeaveResponse struct {
	LeaveID              int32    `protobuf:"varint,1,opt,name=LeaveID,proto3" json:"LeaveID,omitempty"`
	ApplicantID          int32    `protobuf:"varint,2,opt,name=ApplicantID,proto3" json:"ApplicantID,omitempty"`
	ApplicantName        string   `protobuf:"bytes,3,opt,name=ApplicantName,proto3" json:"ApplicantName,omitempty"`
	ApproverID           int32    `protobuf:"varint,4,opt,name=ApproverID,proto3" json:"ApproverID,omitempty"`
	ApproverName         string   `protobuf:"bytes,5,opt,name=ApproverName,proto3" json:"ApproverName,omitempty"`
	StartTime            string   `protobuf:"bytes,6,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              string   `protobuf:"bytes,7,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLeaveResponse) Reset()         { *m = CreateLeaveResponse{} }
func (m *CreateLeaveResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLeaveResponse) ProtoMessage()    {}
func (*CreateLeaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fda2757050484027, []int{1}
}

func (m *CreateLeaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLeaveResponse.Unmarshal(m, b)
}
func (m *CreateLeaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLeaveResponse.Marshal(b, m, deterministic)
}
func (m *CreateLeaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLeaveResponse.Merge(m, src)
}
func (m *CreateLeaveResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLeaveResponse.Size(m)
}
func (m *CreateLeaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLeaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLeaveResponse proto.InternalMessageInfo

func (m *CreateLeaveResponse) GetLeaveID() int32 {
	if m != nil {
		return m.LeaveID
	}
	return 0
}

func (m *CreateLeaveResponse) GetApplicantID() int32 {
	if m != nil {
		return m.ApplicantID
	}
	return 0
}

func (m *CreateLeaveResponse) GetApplicantName() string {
	if m != nil {
		return m.ApplicantName
	}
	return ""
}

func (m *CreateLeaveResponse) GetApproverID() int32 {
	if m != nil {
		return m.ApproverID
	}
	return 0
}

func (m *CreateLeaveResponse) GetApproverName() string {
	if m != nil {
		return m.ApproverName
	}
	return ""
}

func (m *CreateLeaveResponse) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *CreateLeaveResponse) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func init() {
	proto.RegisterEnum("interface.dto.proto.ApprovalTypes", ApprovalTypes_name, ApprovalTypes_value)
	proto.RegisterType((*CreateLeaveRequest)(nil), "interface.dto.proto.CreateLeaveRequest")
	proto.RegisterType((*CreateLeaveResponse)(nil), "interface.dto.proto.CreateLeaveResponse")
}

func init() {
	proto.RegisterFile("interface/facade/rpc/proto/leave.proto", fileDescriptor_fda2757050484027)
}

var fileDescriptor_fda2757050484027 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x5d, 0x4b, 0xeb, 0x40,
	0x10, 0xbd, 0xdb, 0xdb, 0x8f, 0x9b, 0x69, 0x7b, 0x29, 0x5b, 0xc4, 0x20, 0x22, 0x21, 0x88, 0x06,
	0x1f, 0x12, 0xa8, 0x6f, 0xfa, 0x54, 0x9b, 0x28, 0x15, 0xa9, 0x65, 0x2d, 0x3e, 0xf8, 0xe4, 0x9a,
	0x4c, 0xa1, 0xd2, 0x26, 0xeb, 0x66, 0x2d, 0xf8, 0x47, 0xfd, 0x23, 0xfe, 0x01, 0xe9, 0x86, 0xb6,
	0x49, 0x5b, 0xf4, 0x6d, 0xcf, 0x99, 0x33, 0xcb, 0x9c, 0x33, 0x03, 0x27, 0x93, 0x58, 0xa1, 0x1c,
	0xf3, 0x10, 0xbd, 0x31, 0x0f, 0x79, 0x84, 0x9e, 0x14, 0xa1, 0x27, 0x64, 0xa2, 0x12, 0x6f, 0x8a,
	0x7c, 0x8e, 0xae, 0x7e, 0xd3, 0xf6, 0x4a, 0xe7, 0x46, 0x2a, 0xc9, 0x48, 0xfb, 0x93, 0x00, 0xed,
	0x49, 0xe4, 0x0a, 0xef, 0x16, 0x52, 0x86, 0x6f, 0xef, 0x98, 0x2a, 0x6a, 0x41, 0xbd, 0x2b, 0xc4,
	0x74, 0x12, 0xf2, 0x58, 0xf5, 0x7d, 0x93, 0x58, 0xc4, 0xa9, 0xb0, 0x3c, 0x45, 0x8f, 0x00, 0xba,
	0x42, 0xc8, 0x64, 0x8e, 0xb2, 0xef, 0x9b, 0x25, 0x2d, 0xc8, 0x31, 0xf4, 0x1a, 0x1a, 0x19, 0xe2,
	0xd3, 0xd1, 0x87, 0x40, 0xf3, 0xaf, 0x45, 0x9c, 0xff, 0x1d, 0xdb, 0xdd, 0x31, 0x84, 0x9b, 0x17,
	0xa6, 0xac, 0xd0, 0x47, 0x0f, 0xc1, 0x78, 0x50, 0x5c, 0xaa, 0xd1, 0x64, 0x86, 0x66, 0xd9, 0x22,
	0x8e, 0xc1, 0xd6, 0x04, 0x35, 0xa1, 0x16, 0xc4, 0x91, 0xae, 0x55, 0x74, 0x6d, 0x09, 0xed, 0x2f,
	0x02, 0xed, 0x82, 0xb1, 0x54, 0x24, 0x71, 0xaa, 0x3b, 0x34, 0xb1, 0x72, 0xb5, 0x84, 0x9b, 0x9e,
	0x4b, 0xdb, 0x9e, 0x8f, 0xa1, 0xb9, 0x82, 0x03, 0x3e, 0xcb, 0x4c, 0x19, 0xac, 0x48, 0x6e, 0x24,
	0x53, 0xde, 0x4a, 0xc6, 0x5e, 0x26, 0x83, 0x52, 0x7f, 0x92, 0x0d, 0x5e, 0xe0, 0x8a, 0xae, 0xab,
	0x3f, 0xb8, 0xae, 0x15, 0x5c, 0x9f, 0x5d, 0xe8, 0x09, 0xd7, 0x61, 0xd2, 0x26, 0x18, 0xdd, 0xe1,
	0x90, 0xdd, 0x3f, 0xf6, 0x07, 0x37, 0xad, 0x3f, 0xb4, 0x01, 0xff, 0x32, 0x18, 0xf8, 0x2d, 0xb2,
	0x40, 0x2c, 0xb8, 0x0d, 0x7a, 0xa3, 0xc0, 0x6f, 0x95, 0x3a, 0xaf, 0x50, 0xd5, 0x51, 0x48, 0xfa,
	0x0c, 0xf5, 0x5c, 0x74, 0xf4, 0x74, 0xe7, 0xd2, 0xb6, 0xaf, 0xe6, 0xc0, 0xf9, 0x5d, 0x98, 0x6d,
	0xe1, 0x6a, 0xff, 0x69, 0x6f, 0x7d, 0xb5, 0x91, 0x4a, 0x16, 0x27, 0x7b, 0x29, 0x45, 0xf8, 0x52,
	0xd5, 0x3d, 0xe7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x65, 0x8e, 0x44, 0xd5, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LeaverClient is the client API for Leaver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LeaverClient interface {
	CreateLeave(ctx context.Context, in *CreateLeaveRequest, opts ...grpc.CallOption) (*CreateLeaveResponse, error)
}

type leaverClient struct {
	cc *grpc.ClientConn
}

func NewLeaverClient(cc *grpc.ClientConn) LeaverClient {
	return &leaverClient{cc}
}

func (c *leaverClient) CreateLeave(ctx context.Context, in *CreateLeaveRequest, opts ...grpc.CallOption) (*CreateLeaveResponse, error) {
	out := new(CreateLeaveResponse)
	err := c.cc.Invoke(ctx, "/interface.dto.proto.Leaver/CreateLeave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaverServer is the server API for Leaver service.
type LeaverServer interface {
	CreateLeave(context.Context, *CreateLeaveRequest) (*CreateLeaveResponse, error)
}

// UnimplementedLeaverServer can be embedded to have forward compatible implementations.
type UnimplementedLeaverServer struct {
}

func (*UnimplementedLeaverServer) CreateLeave(ctx context.Context, req *CreateLeaveRequest) (*CreateLeaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLeave not implemented")
}

func RegisterLeaverServer(s *grpc.Server, srv LeaverServer) {
	s.RegisterService(&_Leaver_serviceDesc, srv)
}

func _Leaver_CreateLeave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaverServer).CreateLeave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interface.dto.proto.Leaver/CreateLeave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaverServer).CreateLeave(ctx, req.(*CreateLeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Leaver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interface.dto.proto.Leaver",
	HandlerType: (*LeaverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLeave",
			Handler:    _Leaver_CreateLeave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interface/facade/rpc/proto/leave.proto",
}
